version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    # image: ./dockerfile
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'